import Head from "next/head";
import { Inter } from "next/font/google";
import Index from "@/components/notes/index";
import Footer from "@/components/footer/Footer";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Sticky Notes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      
      <Index />
    </>
  );
}
